# Generated by Django 3.0.4 on 2021-01-01 16:32

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fault_List',
            fields=[
                ('Fault_number', models.IntegerField(default=api.models.fault_number_generator, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(choices=[('Harare', (('Mbare', 'Mbare'), ('Waterfalls', 'Waterfalls'), ('cbd', 'cbd'), ('Belvedere', 'Belvedere'), ('Kuwadzana', 'Kuwadzana'), ('GlenView', 'Glenview'), ('Borrowdale', 'Borrowdale'), ('Warren-Park', 'Warren-Park'), ('Budiriro', 'Budiriro'), ('Epworth', 'Epworth'))), ('Mutare', (('Borderview', 'Borderview'), ('Murambi', 'Murambi'), ('Darlington', 'Darlington'), ('Sakubva', 'Sakubva'), ('Chikanga', 'Chikanga'), ('Dangamvura', 'Dangamvura'), ('yeovil', 'Yeovil')))], max_length=200)),
                ('Duration', models.CharField(max_length=30)),
                ('Description', models.TextField(max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('new', 'New'), ('current', 'Current'), ('resolved', 'Resolved'), ('stalled', 'Stalled')], default='new', max_length=20)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=200)),
                ('Province', models.CharField(max_length=200, null=True)),
                ('Description', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='LoadShedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_name', models.CharField(choices=[('Harare', (('Mbare', 'Mbare'), ('Waterfalls', 'Waterfalls'), ('cbd', 'cbd'), ('Belvedere', 'Belvedere'), ('Kuwadzana', 'Kuwadzana'), ('GlenView', 'Glenview'), ('Borrowdale', 'Borrowdale'), ('Warren-Park', 'Warren-Park'), ('Budiriro', 'Budiriro'), ('Epworth', 'Epworth'))), ('Mutare', (('Borderview', 'Borderview'), ('Murambi', 'Murambi'), ('Darlington', 'Darlington'), ('Sakubva', 'Sakubva'), ('Chikanga', 'Chikanga'), ('Dangamvura', 'Dangamvura'), ('yeovil', 'Yeovil')))], max_length=100)),
                ('Duration', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('engaged', 'Engaged'), ('free', 'Free')], default='free', max_length=20)),
                ('Fault_Detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Fault_List')),
            ],
        ),
    ]
