# Generated by Django 3.0.4 on 2021-01-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fault_List',
            new_name='FaultList',
        ),
    ]
