# Generated by Django 3.0.4 on 2021-01-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210119_1854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RenameModel(
            old_name='Incidents',
            new_name='Incident',
        ),
    ]
