# Generated by Django 3.0.4 on 2021-01-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210125_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='Status',
            field=models.CharField(choices=[('current', 'Current'), ('resolved', 'Resolved')], default='Current', max_length=20),
        ),
    ]
